[package]
name = "psina"
version = "0.1.0"
edition = "2021"
description = "Blazzzzingly fast graphql schema generator from prisma file"
license = "Artistic-2.0"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
clap = { version = "3.1.18", features = ["derive"] }
colored = "2.0.0"
